name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for your issue! We're sorry for the incoveniences. A developer will check your issue soon."
        pr-message: "Thank you for your pull request! Contributing is very important to us. A developer will check your pull request soon."
